# Statistics by Michael1011
# Version 1.0.0

ConfigVersion: "1"

CollectMetrics: true
# This plugin collects anonymous statistics (about your Minecraft and Java Version, your system,...) by default.
# Set this to false to disable the tracking.

Interval:
  ServerStats: 5
  # in wich intervall should be stats of the server collected (in minutes, minimum 1)

MySQL:
  host: "localhost"
  port: "3306"
  database: "stats"
  username: "root"
  password: "psswrd"
  # you have to connect to your MySQL server
