main: eu.michael1011.main.Main
name: Statistics
version: 0.1.3
description: Collect stats from your players
author: Michael1011

commands:
  stat:
    usage: "/stat <player>"
    description: "shows the stats of a player"

permissions:
  statistics.show:
    description: "to get data via the /stat command"
    default: op
